services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ratingapp
      POSTGRES_PASSWORD: ratingapp123
      POSTGRES_DB: ratingapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rating_app_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: ratingapp
      DB_PASSWORD: ratingapp123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ratingapp
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
